/**
 * Continent metadata + country → continent map for Location Catalog.
 * Shared by enrich script and client UI.
 */

export const CONTINENTS = [
  { id: "Asia", name: "Asia", emoji: "🌏" },
  { id: "Europe", name: "Europe", emoji: "🌍" },
  { id: "Africa", name: "Africa", emoji: "🌍" },
  { id: "North America", name: "North America", emoji: "🌎" },
  { id: "South America", name: "South America", emoji: "🌎" },
  { id: "Oceania", name: "Oceania", emoji: "🌏" },
  { id: "Antarctica", name: "Antarctica", emoji: "❄" },
] as const;

export type ContinentName = (typeof CONTINENTS)[number]["id"];

/** ISO 3166-1 alpha-2 (and a few territory codes) → continent for World Memory. */
export const CONTINENT_BY_CODE: Record<string, ContinentName> = {
  // Existing catalog
  JP: "Asia",
  KR: "Asia",
  CN: "Asia",
  TW: "Asia",
  HK: "Asia",
  SG: "Asia",
  TH: "Asia",
  VN: "Asia",
  PH: "Asia",
  MY: "Asia",
  ID: "Asia",
  IN: "Asia",
  AU: "Oceania",
  NZ: "Oceania",
  US: "North America",
  CA: "North America",
  MX: "North America",
  BR: "South America",
  AR: "South America",
  CL: "South America",
  CO: "South America",
  PE: "South America",
  GB: "Europe",
  IE: "Europe",
  FR: "Europe",
  DE: "Europe",
  IT: "Europe",
  ES: "Europe",
  PT: "Europe",
  NL: "Europe",
  BE: "Europe",
  CH: "Europe",
  AT: "Europe",
  SE: "Europe",
  NO: "Europe",
  DK: "Europe",
  FI: "Europe",
  PL: "Europe",
  CZ: "Europe",
  GR: "Europe",
  TR: "Asia",
  RU: "Europe",
  UA: "Europe",
  EG: "Africa",
  MA: "Africa",
  ZA: "Africa",
  NG: "Africa",
  KE: "Africa",
  AE: "Asia",
  SA: "Asia",
  IL: "Asia",
  // Expansion — Europe / North Atlantic
  IS: "Europe",
  FO: "Europe",
  GL: "North America",
  SJ: "Europe",
  AX: "Europe",
  MT: "Europe",
  CY: "Asia",
  LU: "Europe",
  ISK: "Europe",
  // Asia
  MN: "Asia",
  KZ: "Asia",
  UZ: "Asia",
  BD: "Asia",
  PK: "Asia",
  LK: "Asia",
  NP: "Asia",
  MM: "Asia",
  KH: "Asia",
  LA: "Asia",
  BN: "Asia",
  MO: "Asia",
  KP: "Asia",
  // Oceania / Pacific
  FJ: "Oceania",
  WS: "Oceania",
  TO: "Oceania",
  VU: "Oceania",
  PW: "Oceania",
  GU: "Oceania",
  MP: "Oceania",
  AS: "Oceania",
  CK: "Oceania",
  NU: "Oceania",
  TV: "Oceania",
  KI: "Oceania",
  MH: "Oceania",
  FM: "Oceania",
  SB: "Oceania",
  PG: "Oceania",
  NC: "Oceania",
  PF: "Oceania",
  WF: "Oceania",
  // Caribbean
  JM: "North America",
  CU: "North America",
  HT: "North America",
  DO: "North America",
  PR: "North America",
  TT: "North America",
  BB: "North America",
  BS: "North America",
  AG: "North America",
  LC: "North America",
  VC: "North America",
  GD: "North America",
  KN: "North America",
  DM: "North America",
  CW: "North America",
  AW: "North America",
  SX: "North America",
  KY: "North America",
  BM: "North America",
  VG: "North America",
  VI: "North America",
  // Americas extras
  CR: "North America",
  PA: "North America",
  GT: "North America",
  HN: "North America",
  SV: "North America",
  NI: "North America",
  BZ: "North America",
  UY: "South America",
  PY: "South America",
  BO: "South America",
  EC: "South America",
  VE: "South America",
  GY: "South America",
  SR: "South America",
  GF: "South America",
  FK: "South America",
  // Africa extras
  ET: "Africa",
  GH: "Africa",
  TZ: "Africa",
  UG: "Africa",
  RW: "Africa",
  SN: "Africa",
  CI: "Africa",
  CM: "Africa",
  AO: "Africa",
  MZ: "Africa",
  MG: "Africa",
  MU: "Africa",
  SC: "Africa",
  CV: "Africa",
  RE: "Africa",
  YT: "Africa",
  // Antarctica
  AQ: "Antarctica",
};

export function continentForCode(code: string): ContinentName {
  return CONTINENT_BY_CODE[code.toUpperCase()] || "Asia";
}
