import fs from "node:fs";
import path from "node:path";

const places = [
  { locationId: "JP:hokkaido", country: "Japan", name: "Hokkaido", lat: 43.06, lng: 141.35 },
  { locationId: "JP:tokyo", country: "Japan", name: "Tokyo", lat: 35.68, lng: 139.76 },
  { locationId: "JP:osaka", country: "Japan", name: "Osaka", lat: 34.69, lng: 135.5 },
  { locationId: "JP:fukuoka", country: "Japan", name: "Fukuoka", lat: 33.59, lng: 130.4 },
  { locationId: "JP:okinawa", country: "Japan", name: "Okinawa", lat: 26.21, lng: 127.68 },
  { locationId: "US:nyc", country: "United States", name: "New York", lat: 40.71, lng: -74.01 },
  { locationId: "US:la", country: "United States", name: "Los Angeles", lat: 34.05, lng: -118.24 },
  { locationId: "US:chicago", country: "United States", name: "Chicago", lat: 41.88, lng: -87.63 },
  { locationId: "US:hawaii", country: "United States", name: "Hawaii", lat: 21.31, lng: -157.86 },
  { locationId: "US:sanfrancisco", country: "United States", name: "San Francisco", lat: 37.77, lng: -122.42 },
  { locationId: "GB:london", country: "United Kingdom", name: "London", lat: 51.51, lng: -0.13 },
  { locationId: "FR:paris", country: "France", name: "Paris", lat: 48.86, lng: 2.35 },
  { locationId: "KR:seoul", country: "South Korea", name: "Seoul", lat: 37.57, lng: 126.98 },
  { locationId: "TW:taipei", country: "Taiwan", name: "Taipei", lat: 25.03, lng: 121.57 },
  { locationId: "AU:sydney", country: "Australia", name: "Sydney", lat: -33.87, lng: 151.21 },
  { locationId: "AU:melbourne", country: "Australia", name: "Melbourne", lat: -37.81, lng: 144.96 },
  { locationId: "CA:toronto", country: "Canada", name: "Toronto", lat: 43.65, lng: -79.38 },
  { locationId: "CA:vancouver", country: "Canada", name: "Vancouver", lat: 49.28, lng: -123.12 },
  { locationId: "DE:berlin", country: "Germany", name: "Berlin", lat: 52.52, lng: 13.41 },
  { locationId: "DE:munich", country: "Germany", name: "Munich", lat: 48.14, lng: 11.58 },
  { locationId: "IT:rome", country: "Italy", name: "Rome", lat: 41.9, lng: 12.5 },
  { locationId: "IT:milan", country: "Italy", name: "Milan", lat: 45.46, lng: 9.19 },
  { locationId: "ES:madrid", country: "Spain", name: "Madrid", lat: 40.42, lng: -3.7 },
  { locationId: "ES:barcelona", country: "Spain", name: "Barcelona", lat: 41.39, lng: 2.17 },
  { locationId: "NL:amsterdam", country: "Netherlands", name: "Amsterdam", lat: 52.37, lng: 4.9 },
  { locationId: "BE:brussels", country: "Belgium", name: "Brussels", lat: 50.85, lng: 4.35 },
  { locationId: "CH:zurich", country: "Switzerland", name: "Zurich", lat: 47.37, lng: 8.54 },
  { locationId: "AT:vienna", country: "Austria", name: "Vienna", lat: 48.21, lng: 16.37 },
  { locationId: "SE:stockholm", country: "Sweden", name: "Stockholm", lat: 59.33, lng: 18.07 },
  { locationId: "NO:oslo", country: "Norway", name: "Oslo", lat: 59.91, lng: 10.75 },
  { locationId: "DK:copenhagen", country: "Denmark", name: "Copenhagen", lat: 55.68, lng: 12.57 },
  { locationId: "FI:helsinki", country: "Finland", name: "Helsinki", lat: 60.17, lng: 24.94 },
  { locationId: "PL:warsaw", country: "Poland", name: "Warsaw", lat: 52.23, lng: 21.01 },
  { locationId: "CZ:prague", country: "Czech Republic", name: "Prague", lat: 50.08, lng: 14.44 },
  { locationId: "HU:budapest", country: "Hungary", name: "Budapest", lat: 47.5, lng: 19.04 },
  { locationId: "GR:athens", country: "Greece", name: "Athens", lat: 37.98, lng: 23.73 },
  { locationId: "PT:lisbon", country: "Portugal", name: "Lisbon", lat: 38.72, lng: -9.14 },
  { locationId: "IE:dublin", country: "Ireland", name: "Dublin", lat: 53.35, lng: -6.26 },
  { locationId: "RU:moscow", country: "Russia", name: "Moscow", lat: 55.76, lng: 37.62 },
  { locationId: "RU:saintpetersburg", country: "Russia", name: "Saint Petersburg", lat: 59.93, lng: 30.32 },
  { locationId: "TR:istanbul", country: "Turkey", name: "Istanbul", lat: 41.01, lng: 28.98 },
  { locationId: "IL:telaviv", country: "Israel", name: "Tel Aviv", lat: 32.09, lng: 34.78 },
  { locationId: "AE:dubai", country: "United Arab Emirates", name: "Dubai", lat: 25.2, lng: 55.27 },
  { locationId: "SA:riyadh", country: "Saudi Arabia", name: "Riyadh", lat: 24.71, lng: 46.68 },
  { locationId: "IN:mumbai", country: "India", name: "Mumbai", lat: 19.08, lng: 72.88 },
  { locationId: "IN:delhi", country: "India", name: "Delhi", lat: 28.61, lng: 77.21 },
  { locationId: "IN:bangalore", country: "India", name: "Bangalore", lat: 12.97, lng: 77.59 },
  { locationId: "PK:karachi", country: "Pakistan", name: "Karachi", lat: 24.86, lng: 67.01 },
  { locationId: "BD:dhaka", country: "Bangladesh", name: "Dhaka", lat: 23.81, lng: 90.41 },
  { locationId: "TH:bangkok", country: "Thailand", name: "Bangkok", lat: 13.76, lng: 100.5 },
  { locationId: "VN:hanoi", country: "Vietnam", name: "Hanoi", lat: 21.03, lng: 105.85 },
  { locationId: "VN:hochiminh", country: "Vietnam", name: "Ho Chi Minh City", lat: 10.82, lng: 106.63 },
  { locationId: "MY:kualalumpur", country: "Malaysia", name: "Kuala Lumpur", lat: 3.14, lng: 101.69 },
  { locationId: "SG:singapore", country: "Singapore", name: "Singapore", lat: 1.35, lng: 103.82 },
  { locationId: "ID:jakarta", country: "Indonesia", name: "Jakarta", lat: -6.21, lng: 106.85 },
  { locationId: "PH:manila", country: "Philippines", name: "Manila", lat: 14.6, lng: 120.98 },
  { locationId: "CN:beijing", country: "China", name: "Beijing", lat: 39.9, lng: 116.41 },
  { locationId: "CN:shanghai", country: "China", name: "Shanghai", lat: 31.23, lng: 121.47 },
  { locationId: "HK:hongkong", country: "Hong Kong", name: "Hong Kong", lat: 22.32, lng: 114.17 },
  { locationId: "MN:ulaanbaatar", country: "Mongolia", name: "Ulaanbaatar", lat: 47.89, lng: 106.91 },
  { locationId: "KZ:almaty", country: "Kazakhstan", name: "Almaty", lat: 43.24, lng: 76.95 },
  { locationId: "NZ:auckland", country: "New Zealand", name: "Auckland", lat: -36.85, lng: 174.76 },
  { locationId: "NZ:wellington", country: "New Zealand", name: "Wellington", lat: -41.29, lng: 174.78 },
  { locationId: "MX:mexicocity", country: "Mexico", name: "Mexico City", lat: 19.43, lng: -99.13 },
  { locationId: "MX:cancun", country: "Mexico", name: "Cancun", lat: 21.16, lng: -86.85 },
  { locationId: "BR:saopaulo", country: "Brazil", name: "São Paulo", lat: -23.55, lng: -46.63 },
  { locationId: "BR:rio", country: "Brazil", name: "Rio de Janeiro", lat: -22.91, lng: -43.17 },
  { locationId: "AR:buenosaires", country: "Argentina", name: "Buenos Aires", lat: -34.6, lng: -58.38 },
  { locationId: "CL:santiago", country: "Chile", name: "Santiago", lat: -33.45, lng: -70.67 },
  { locationId: "CO:bogota", country: "Colombia", name: "Bogotá", lat: 4.71, lng: -74.07 },
  { locationId: "PE:lima", country: "Peru", name: "Lima", lat: -12.05, lng: -77.04 },
  { locationId: "EG:cairo", country: "Egypt", name: "Cairo", lat: 30.04, lng: 31.24 },
  { locationId: "MA:casablanca", country: "Morocco", name: "Casablanca", lat: 33.57, lng: -7.59 },
  { locationId: "ZA:capeTown", country: "South Africa", name: "Cape Town", lat: -33.92, lng: 18.42 },
  { locationId: "ZA:johannesburg", country: "South Africa", name: "Johannesburg", lat: -26.2, lng: 28.04 },
  { locationId: "NG:lagos", country: "Nigeria", name: "Lagos", lat: 6.52, lng: 3.38 },
  { locationId: "KE:nairobi", country: "Kenya", name: "Nairobi", lat: -1.29, lng: 36.82 },
  { locationId: "ET:addisababa", country: "Ethiopia", name: "Addis Ababa", lat: 9.03, lng: 38.74 },
  { locationId: "IS:reykjavik", country: "Iceland", name: "Reykjavik", lat: 64.13, lng: -21.82 },
  { locationId: "GL:nuuk", country: "Greenland", name: "Nuuk", lat: 64.18, lng: -51.72 },
  { locationId: "CU:havana", country: "Cuba", name: "Havana", lat: 23.11, lng: -82.37 },
  { locationId: "PR:sanjuan", country: "Puerto Rico", name: "San Juan", lat: 18.47, lng: -66.11 },
  { locationId: "QA:doha", country: "Qatar", name: "Doha", lat: 25.29, lng: 51.53 },
  { locationId: "IR:tehran", country: "Iran", name: "Tehran", lat: 35.69, lng: 51.39 },
  { locationId: "JO:amman", country: "Jordan", name: "Amman", lat: 31.95, lng: 35.93 },
  { locationId: "LK:colombo", country: "Sri Lanka", name: "Colombo", lat: 6.93, lng: 79.85 },
  { locationId: "NP:kathmandu", country: "Nepal", name: "Kathmandu", lat: 27.72, lng: 85.32 },
  { locationId: "MM:yangon", country: "Myanmar", name: "Yangon", lat: 16.87, lng: 96.2 },
  { locationId: "KH:phnompenh", country: "Cambodia", name: "Phnom Penh", lat: 11.56, lng: 104.92 },
  { locationId: "UZ:tashkent", country: "Uzbekistan", name: "Tashkent", lat: 41.3, lng: 69.28 },
  { locationId: "GE:tbilisi", country: "Georgia", name: "Tbilisi", lat: 41.72, lng: 44.78 },
  { locationId: "UA:kyiv", country: "Ukraine", name: "Kyiv", lat: 50.45, lng: 30.52 },
  { locationId: "RO:bucharest", country: "Romania", name: "Bucharest", lat: 44.43, lng: 26.1 },
  { locationId: "HR:zagreb", country: "Croatia", name: "Zagreb", lat: 45.81, lng: 15.98 },
  { locationId: "RS:belgrade", country: "Serbia", name: "Belgrade", lat: 44.79, lng: 20.45 },
  { locationId: "EE:tallinn", country: "Estonia", name: "Tallinn", lat: 59.44, lng: 24.75 },
  { locationId: "LV:riga", country: "Latvia", name: "Riga", lat: 56.95, lng: 24.11 },
  { locationId: "LT:vilnius", country: "Lithuania", name: "Vilnius", lat: 54.69, lng: 25.28 },
  { locationId: "TN:tunis", country: "Tunisia", name: "Tunis", lat: 36.81, lng: 10.18 },
  { locationId: "DZ:algiers", country: "Algeria", name: "Algiers", lat: 36.75, lng: 3.06 },
  { locationId: "GH:accra", country: "Ghana", name: "Accra", lat: 5.56, lng: -0.2 },
  { locationId: "SN:dakar", country: "Senegal", name: "Dakar", lat: 14.72, lng: -17.47 },
  { locationId: "TZ:dar", country: "Tanzania", name: "Dar es Salaam", lat: -6.79, lng: 39.28 },
  { locationId: "MU:portlouis", country: "Mauritius", name: "Port Louis", lat: -20.16, lng: 57.5 },
  { locationId: "FJ:suva", country: "Fiji", name: "Suva", lat: -18.14, lng: 178.44 },
];

const root = path.resolve("data/world-places");
fs.mkdirSync(root, { recursive: true });
const json = JSON.stringify({ places }, null, 2);
fs.writeFileSync(path.join(root, "places.json"), json);
fs.writeFileSync(path.join("public/locations/places.json"), json);
console.log(`Wrote ${places.length} places`);
